line-length = 88
target-version = "py311"

[lint]
select = [
  "B",   # bugbear
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # import order
  "RUF",
  "UP",  # pyupgrade
  "W",   # pycodestyle warnings
]
